# Generated by Django 4.1.5 on 2023-01-30 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Rangel_portfolio", "0004_alter_product_img"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="img",
            field=models.ImageField(
                default="static/images/_0.jpg", upload_to="images/"
            ),
        ),
    ]
