# Generated by Django 4.1.5 on 2023-01-30 21:17

import Rangel_portfolio.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Rangel_portfolio", "0009_alter_product_img"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="img",
            field=models.ImageField(
                default="static/images/default.jpg",
                upload_to=Rangel_portfolio.models.generate_image_filename,
            ),
        ),
    ]
