# Generated by Django 4.0.4 on 2023-04-03 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Rangel_portfolio', '0011_product_canvas'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='category',
            new_name='categories',
        ),
    ]
