# Generated by Django 4.1.5 on 2023-01-29 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=350, null=True)),
                ("content", models.TextField(max_length=10000, null=True)),
                (
                    "img",
                    models.ImageField(
                        default="images/default/_0.jpg", upload_to="images/"
                    ),
                ),
            ],
        ),
    ]
