# Generated by Django 4.1.5 on 2023-01-30 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Rangel_portfolio", "0002_product_category_product_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.CharField(
                choices=[
                    ("Category1", "Category1"),
                    ("Category2", "Category2"),
                    ("Category3", "Category3"),
                ],
                default=1,
                max_length=350,
            ),
        ),
    ]
