# Generated by Django 4.1.5 on 2023-01-30 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Rangel_portfolio", "0003_alter_product_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="img",
            field=models.ImageField(default="images/_0.jpg", upload_to="images/"),
        ),
    ]
