# Generated by Django 4.0.4 on 2023-04-03 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rangel_portfolio', '0012_rename_category_product_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='categories',
            field=models.CharField(choices=[('category1', 'category1'), ('category2', 'category2'), ('category3', 'category3')], default=1, max_length=350),
        ),
    ]
