# Generated by Django 4.0.4 on 2023-04-24 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rangel_portfolio', '0015_alter_product_canvas_alter_product_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='categories',
            field=models.CharField(choices=[('Oil-Painting', 'Oil-Painting'), ('Watercolors', 'Watercolors'), ('Dry Crayons', 'Dry Crayons'), ('Oil Crayons', 'Oil Crayons')], default=1, max_length=350),
        ),
    ]
