# Generated by Django 4.1.7 on 2023-05-02 04:57

import Rangel_portfolio.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rangel_portfolio', '0019_alter_product_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='img',
            field=models.ImageField(default='images/default.jpg', upload_to=Rangel_portfolio.models.generate_image_filename),
        ),
    ]
