# Generated by Django 4.1.5 on 2023-07-16 06:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Rangel_portfolio", "0022_alter_product_img"),
    ]

    operations = [
        migrations.CreateModel(
            name="FormData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("context", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
