# Generated by Django 4.2.4 on 2024-02-11 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rangel_portfolio', '0022_alter_product_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='default', max_length=50)),
                ('email', models.CharField(default='default', max_length=250)),
                ('content', models.TextField(max_length=10000, null=True)),
            ],
        ),
    ]
