# Generated by Django 4.2.4 on 2024-02-11 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rangel_portfolio', '0024_purchaseemail_send_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseemail',
            name='send_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Received_At'),
        ),
    ]
