# Generated by Django 4.2.4 on 2024-02-11 09:44

import Rangel_portfolio.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rangel_portfolio', '0025_alter_purchaseemail_send_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='uploadImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canvas', models.CharField(default=1, max_length=350)),
                ('categories', models.CharField(default=1, max_length=350)),
                ('name', models.CharField(max_length=350, null=True)),
                ('title', models.CharField(max_length=350, null=True)),
                ('content', models.TextField(max_length=10000, null=True)),
                ('custom_filename', models.CharField(default='default', max_length=250)),
                ('img', models.ImageField(default='images/default.jpg', upload_to=Rangel_portfolio.models.generate_image_filename)),
            ],
        ),
    ]
