# Generated by Django 4.2.4 on 2024-02-11 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Rangel_portfolio', '0027_alter_uploadimages_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='uploadImages',
        ),
    ]
